# Generated by Django 5.2.9 on 2026-02-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_event_time_alter_event_date_alter_event_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=100)),
                ('russian', models.CharField(max_length=100)),
                ('transcription', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
