# Generated by Django 5.2.9 on 2026-02-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_vocabulary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='translation',
            new_name='russian',
        ),
        migrations.RemoveField(
            model_name='word',
            name='added_on',
        ),
        migrations.RemoveField(
            model_name='word',
            name='user',
        ),
        migrations.AddField(
            model_name='word',
            name='transcription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
