# Generated by Django 5.2.9 on 2026-02-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_lesson_lesson_progress_alter_lesson_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
