# Generated by Django 5.2.9 on 2026-02-24 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_lesson_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='progress',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='main.lesson'),
        ),
    ]
